---
title: "APIM"
author: "Emma Livingston"
date: "11/29/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psysds364data)
library(tidyverse)
library(psych)
library(nlme)
library(mosaic)
library(stargazer)

```


```{r select_variables}
Goldberg_gav_sm <- Goldberg_gav %>%
  select(ID,
         Partner,
         group,
         gender,
         h12selfdir,
         #h12conform,
         SocComp
         )
```

```{r subset_data}
#exclude individuals who do not have data for parental values or social competence

#find the subset of dyads who have information for both people for all of the variables
Goldberg_gav_completes <- Goldberg_gav_sm %>%
  filter(!is.na(SocComp) & !is.na(h12selfdir)) %>%
  group_by(ID) %>%
  count() %>%
  filter(n == 2)

#join this subset with the full set of individuals
Goldberg_gav_sm <- Goldberg_gav_sm %>%
  inner_join(Goldberg_gav_completes, by = "ID")
```


```{r impute_data}
#impute gender 3 to gender 1
Goldberg_gav_sm <- Goldberg_gav_sm %>%
  #mutate(w11RelDur = ifelse(ID == 231 & Partner == 2, 7.0, w11RelDur)) %>%
  mutate(gender = ifelse(gender == 3, 1, gender))

#NA gender goes to 1
Goldberg_gav_sm$gender[is.na(Goldberg_gav_sm$gender)] <- 1
```

```{r}
#Impute partner number for second person in dyad 53:
Goldberg_gav_sm[38, 2] = 2
#Impute partner number for second person in dyad 247:
Goldberg_gav_sm[153, 2] = 1

# Pairwise data
tempA <- Goldberg_gav_sm %>%
  mutate(
    genderE = gender,
    partnum = 1,
    Partner = case_when(
      Partner == 1 ~ "A",
      Partner == 2 ~ "P")) %>%
  select(-n) %>%
  gather(variable, value, group:genderE) %>%
  unite(var_partner, variable, Partner) %>%
  spread(var_partner, value)

tempB <- Goldberg_gav_sm %>%
  mutate(
    genderE = gender,
    partnum = 2,
    Partner = case_when(
      Partner == 1 ~ "P",
      Partner == 2 ~ "A")) %>%
  select(-n, -gender, group) %>%
  gather(variable, value, group:genderE) %>%
  unite(var_partner, variable, Partner) %>%
  spread(var_partner, value)

pairwise <- bind_rows(tempA, tempB) %>%
  select(-gender_A, -gender_P, -group_P) %>%
  rename(group = group_A) %>%
  arrange(ID) %>%
  janitor::clean_names()


```



# Moderator 

We first center the moderator and predictor variables:

```{r}
pairwise <- pairwise %>%
  mutate(h12selfdir_a_ctr = h12selfdir_a - mean(h12selfdir_a),
         h12selfdir_p_ctr = h12selfdir_p - mean(h12selfdir_p),
         soc_comp_a_ctr = soc_comp_a - mean(soc_comp_a),
         soc_comp_p_ctr = soc_comp_p - mean(soc_comp_p))

pairwise <- pairwise %>%
  mutate(samesex = ifelse(group == 1 | group == 2, 1, 0))

```

We then estimate the two-intercept model:

```{r}

#simply use the group variable
moderation <- gls(soc_comp_a ~ as.factor(group) +
                    h12selfdir_a_ctr:as.factor(group) +
                    h12selfdir_p_ctr:as.factor(group) - 1,
                  data = pairwise,
                  correlation = corCompSymm(form = ~1|id),
                  na.action = na.omit)

summary(moderation)
coef(summary(moderation))

moderation2 <- gls(soc_comp_a ~ as.factor(samesex) +
                    h12selfdir_a_ctr:as.factor(samesex) +
                    h12selfdir_p_ctr:as.factor(samesex) - 1,
                  data = pairwise,
                  correlation = corCompSymm(form = ~1|id),
                  na.action = na.omit)

summary(moderation2)
coef(summary(moderatio2n))

moderation_test <- gls(soc_comp_a ~ h12selfdir_a_ctr*as.factor(samesex) +
                    h12selfdir_p_ctr*as.factor(samesex),
                  data = pairwise,
                  correlation = corCompSymm(form = ~1|id),
                  na.action = na.omit)

summary(moderation_test)

coef(summary(moderation_test))
```


```{r}
pairwise <- pairwise %>%
  mutate(h12selfdir_a_ctrhigh = h12selfdir_a_ctr - sd(h12selfdir_a_ctr),
         h12selfdir_p_ctrhigh = h12selfdir_p_ctr - sd(h12selfdir_p_ctr),
         h12selfdir_a_ctrlow = h12selfdir_a_ctr + sd(h12selfdir_a_ctr),
         h12selfdir_p_ctrlow = h12selfdir_p_ctr + sd(h12selfdir_p_ctr))

```

```{r}
a_high <- gls(soc_comp_a ~ as.factor(samesex) +
                h12selfdir_a_ctrhigh:as.factor(samesex) +
                h12selfdir_p_ctr:as.factor(samesex) - 1,
              data = pairwise,
              correlation = corCompSymm(form = ~1|id))

summary(a_high)

a_low <- gls(soc_comp_a ~ as.factor(samesex) +
                h12selfdir_a_ctrlow:as.factor(samesex) +
                h12selfdir_p_ctr:as.factor(samesex) - 1,
              data = pairwise,
              correlation = corCompSymm(form = ~1|id))

summary(a_low)

p_high <- gls(soc_comp_a ~ as.factor(samesex) +
                h12selfdir_a_ctr:as.factor(samesex) +
                h12selfdir_p_ctrhigh:as.factor(samesex) - 1,
              data = pairwise,
              correlation = corCompSymm(form = ~1|id))

summary(p_high)

p_low <- gls(soc_comp_a ~ as.factor(samesex) +
                h12selfdir_a_ctr:as.factor(samesex) +
                h12selfdir_p_ctrlow:as.factor(samesex) - 1 ,
              data = pairwise,
              correlation = corCompSymm(form = ~1|id))

summary(p_low)
```

```{r}
stargazer(moderation2, title="Regression results for parental values of self-direction",
align=TRUE, dep.var.labels=c("Perception of child's social competence"), covariate.labels=c("Heterosexual couples","Same-sex couples",
"Heterosexual couple actor effect","Same-sex couple actor effect", "Heterosexual couple partner effect","Same-sex couple partner effect"),
 no.space=TRUE, single.row=TRUE, keep.stat = c("rsq", "ser", "n"), type = "latex")
```



