---
title: "Data Wrangling"
author: "Emma Livingston"
date: "11/25/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(psysds364data)
```


```{r select_variables}
Goldberg_gav_sm <- Goldberg_gav %>%
  select(ID,
         Partner,
         group,
         gender,
         h12selfdir,
         #h12conform,
         SocComp
         )
```

```{r subset_data}
#exclude individuals who do not have data for parental values or social competence

#find the subset of dyads who have information for both people for all of the variables
Goldberg_gav_completes <- Goldberg_gav_sm %>%
  filter(!is.na(SocComp) & !is.na(h12selfdir)) %>%
  group_by(ID) %>%
  count() %>%
  filter(n == 2)

#join this subset with the full set of individuals
Goldberg_gav_sm <- Goldberg_gav_sm %>%
  inner_join(Goldberg_gav_completes, by = "ID")
```


```{r impute_data}
#impute gender 3 to gender 1
Goldberg_gav_sm <- Goldberg_gav_sm %>%
  #mutate(w11RelDur = ifelse(ID == 231 & Partner == 2, 7.0, w11RelDur)) %>%
  mutate(gender = ifelse(gender == 3, 1, gender))

#NA gender goes to 1
Goldberg_gav_sm$gender[is.na(Goldberg_gav_sm$gender)] <- 1
```

```{r}
#Impute partner number for second person in dyad 53:
Goldberg_gav_sm[38, 2] = 2
#Impute partner number for second person in dyad 247:
Goldberg_gav_sm[153, 2] = 1

# Pairwise data
tempA <- Goldberg_gav_sm %>%
  mutate(
    genderE = gender,
    partnum = 1,
    Partner = case_when(
      Partner == 1 ~ "A",
      Partner == 2 ~ "P")) %>%
  select(-n) %>%
  gather(variable, value, group:genderE) %>%
  unite(var_partner, variable, Partner) %>%
  spread(var_partner, value)

tempB <- Goldberg_gav_sm %>%
  mutate(
    genderE = gender,
    partnum = 2,
    Partner = case_when(
      Partner == 1 ~ "P",
      Partner == 2 ~ "A")) %>%
  select(-n, -gender, group) %>%
  gather(variable, value, group:genderE) %>%
  unite(var_partner, variable, Partner) %>%
  spread(var_partner, value)

pairwise <- bind_rows(tempA, tempB) %>%
  select(-gender_A, -gender_P, -group_P) %>%
  rename(group = group_A) %>%
  arrange(ID) %>%
  janitor::clean_names()


```